### ISSUE TITLE
offsets and rescaling in models for counts

### ISSUE THREAD

**Issue by lzachmann** [lzachmann/models-for-missing-data#5]
Need to craft a post for the website and update the model API to reflect some of the basic logic here, time permitting:

```R
library(tidyverse)
library(R2jags)

# Constants ('sampling design').
n_plots <- 250 # the number of observations (one per plot)
sq_m_per_plot <- c(big_plot = 20 * 50, small_plot = 10 * 25) # the size of each plot
sq_m_per_acre <- 4046.86 # the desired inferential unit (acres)

# Generating values.
avg_n_trees_per_sq_m <- 0.05

# Other required quantities.
n_plots_per_acre <- sq_m_per_acre / sq_m_per_plot

# Parameters.
exp_b0 <- avg_n_trees_per_sq_m * sq_m_per_plot # the mean of the response when x is 0
exp_b1 <- 1.1 # the multiplicative change in the response per unit change (sd) in x

b0 <- log(exp_b0)
b1 <- log(exp_b1)

# Draw a sample of `n_plots` according to the cost to sample a plot, which we'll 
# assume scales with the area of the plot.
d <- crossing(obs_idx = seq_len(n_plots), exposure = sq_m_per_plot) %>%
  sample_n(n_plots, weight = 1 / exposure) %>%
  mutate(
    # Simulate the x's as a unit normal, then y conditional on the x's.
    b0 = log(avg_n_trees_per_sq_m * exposure), b1 = b1, 
    x1 = rnorm(n_plots), lambda = exp(b0 + b1 * x1), y = rpois(n(), lambda)
  ) # hist(d$y, breaks = 30)

# The model.
m <- function() {
  for(i in 1:N) {
    y[i] ~ dpois(lambda[i])
    lambda[i] <- exp(b0 + b1 * x1[i]) * offset[i] / r
  }
  b0 ~ dnorm(0, 1 / 50^2)
  b1 ~ dnorm(0, 1 / 10^2)
}

fit <- jags(
  
  # offset options: rep(1, nrow(d)), d$exposure (caveat: 1 can't be used if plot sizes vary!)
  # if offset == 1, parameters are on the plot scale
  # if offset == d$exposure, parameters are per m^2
  
  # r: a scalar to arbitrarily rescale parameter values, depends too on offset
  # use original units per desired units
  # if offset == 1 and r == n_plots_per_acre, params will be on per acre scale
  # if offset == d$exposure, then r has to be sq_m_per_acre to get per acre scale params
  
  # data = list(N = nrow(d), y = d$y, x1 = d$x1, offset = d$exposure, r = 1),
  data = list(N = nrow(d), y = d$y, x1 = d$x1, offset = d$exposure, r = sq_m_per_acre),

  inits = function(){
    list("b0" = rnorm(1), "b1" = rnorm(1))
  },
  parameters.to.save = c('b0', 'b1'), 
  n.chains = 3, n.iter = 15000, n.burnin = 5000, n.thin = 5,
  model.file = m, DIC = FALSE
)

print(fit)
# range(fit$BUGSoutput$sims.list$b0)
posts <- as_tibble(fit$BUGSoutput$sims.matrix) %>% 
  mutate(lambda_x1_eq_0 = exp(b0), lambda_x1_eq_1 = exp(b0 + b1 * 1),
         # lambda_diff = lambda_x1_eq_1 - lambda_x1_eq_0, 
         lambda_perc_change = (lambda_x1_eq_1 - lambda_x1_eq_0) / lambda_x1_eq_0 * 100) %>% 
  # mutate(across(all_of(c("b0", "b1")), exp)) %>% 
  pivot_longer(everything())

ggplot(posts) +
  facet_wrap(~name, scales = 'free') +
  geom_histogram(
    aes(x = value, y = ..density..), color = 'black', fill = 'white', bins = 50
  )
```

Should be relatively trivial to add the equivalent of `<lamba_unscaled> * offset[i] / r`(from the model above) to appropriate files in the model builder tree. Still need to determine what, if anything, changes as the deterministic model changes. And need to develop a reasonably intuitive user interface via the config files for specifying such models. Errors made during unit conversion could lead to stunningly erroneous inference, so need to be absolutely sure values supplied by the user lead to the intended transformation(s).

Here's an insufficient proposal to kick things off.
```yml
# The offset (default 1). Anything other than 1 will rescale parameters. The offset *must* be
# included if the length, size, duration, or intensity of sampling varies across observations. 
# We recommend leaving this at its default value unless this is the case.
offset: 1
# The rescaling term allows the analyst to express parameters in more meaningful units. Say
# your counts were made exclusively on 20m by 50m plots, but you want estimates on a per 
# acre scale, this term is entered as the number of plots per acre, ~4.04686, where 
# `plots_per_acre = sq_m_per_acre / sq_m_per_plot` and `sq_m_per_acre` = 4046.86.
rescaling term: 4.04686
```
Note that in the R code above, _both_ of these terms are in play at the same time. We use the offset term to deal with varying plots sizes, and then use the rescaling term to express the result on the per acre scale.
